/*
* @Author: anchen
* @Date:   2017-01-06 23:33:32
* @Last Modified by:   anchen
* @Last Modified time: 2017-01-09 14:40:48
*/

'use strict';
var dataList = [
        {
            img:'img/1.jpg',
            caption:'美图001',
            desc:'当一个女孩向你倾诉她的烦恼，那不是抱怨，那是她对你的信任。因为没有一个女的愿意跟不喜欢的男的废话。'
        },
        {
            img:'img/2.jpg',
            caption:'美图002',
            desc:'我微笑。在任何我难过或者快乐的时候，我只剩下微笑。'
        },
        {
            img:'img/3.jpg',
            caption:'美图003',
            desc:'人的寂寞，有时候很难用语言表达。'
        },
        {
            img:'img/4.jpg',
            caption:'美图004',
            desc:'喜欢的就要拥有它，不要害怕结果。'
        },
        {
            img:'img/5.jpg',
            caption:'美图005',
            desc:'我大概是一只鸟。充满了警觉，不容易停留。所以一直在飞。'
        },
        {
            img:'img/6.jpg',
            caption:'美图006',
            desc:'那些美丽的小鱼，它们睡觉的时候也睁着眼睛。不需要爱情，亦从不哭泣。它们是我的榜样。'
        },
        {
            img:'img/7.jpg',
            caption:'美图007',
            desc:'爱情是容易被怀疑的幻觉，一旦被识破就自动灰飞烟灭。'
        },
        {
            img:'img/8.jpg',
            caption:'美图008',
            desc:'我会惧怕孤独吗?我只是偶尔会感觉寂寞。'
        },
        {
            img:'img/9.jpg',
            caption:'美图009',
            desc:'有些事情在劫难逃。'
        },
        {
            img:'img/10.jpg',
            caption:'美图010',
            desc:'会过去的，就会过去的。我们的痛苦，我们的悲伤，我们的负罪。'
        },
        {
            img:'img/11.jpg',
            caption:'美图011',
            desc:'我的世界是寂静无声的，容纳不下别人。'
        },
        {
            img:'img/12.jpg',
            caption:'美图012',
            desc:'你完全没必要害怕，你可以选择不回答——就当欠我一个拥抱'
        },
        {
            img:'img/13.jpg',
            caption:'美图013',
            desc:'其实，世界上最浪漫的事，并不是什么烛光晚餐，而是，我喜欢你，恰巧，你也来到了我身边……'
        },
        {
            img:'img/14.jpg',
            caption:'美图014',
            desc:'越过春秋冬夏，赴一日之约'
        },
        {
            img:'img/15.jpg',
            caption:'美图015',
            desc:'你站的方向吹过来的风是暖的'
        },
        {
            img:'img/16.jpg',
            caption:'美图016',
            desc:'你站在桥上看风景，看风景的人在楼上看你'
        },
        {
            img:'img/17.jpg',
            caption:'美图017',
            desc:'就算终有一散，也别辜负相遇'
        },
        {
            img:'img/18.jpg',
            caption:'美图018',
            desc:'愿时光许你，佑你岁月无忧'
        },
        {
            img:'img/19.jpg',
            caption:'美图019',
            desc:'生不对，死不起。'
        },
        {
            img:'img/20.jpg',
            caption:'美图020',
            desc:'有这样一种幸福'
        },
        {
            img:'img/21.jpg',
            caption:'美图021',
            desc:'最温暖人心的莫过于陪伴。'
        }
    ];